/**
 * Background script for Teachme Learning Assistant
 * Handles extension-wide functionality and communication between components
 */

// Initialize the extension when installed
chrome.runtime.onInstalled.addListener(() => {
  console.log('Teachme Learning Assistant installed');
  
  // Initialize storage with default settings
  chrome.storage.local.set({
    settings: {
      voiceRate: 1.0,      // Speech rate (1.0 is normal speed)
      voicePitch: 1.0,     // Speech pitch (1.0 is normal pitch)
      maxContentLength: 5000, // Maximum content length to process
      apiKey: '',          // Will need to be set by the user
      apiProvider: 'openai', // Default API provider
      apiModel: 'gpt-3.5-turbo', // Default model
      useSimulation: true, // Use simulation mode by default (until API key is set)
    },
    history: []           // Will store history of explanations
  });
});

// Listen for messages from popup or content scripts
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  // Handle different types of messages
  
  if (request.action === 'processContent') {
    // Get settings to check if we should use simulation or real API
    chrome.storage.local.get('settings', async (data) => {
      const settings = data.settings || {};
      
      try {
        let response;
        
        // Check if we should use simulation or real API
        if (settings.useSimulation || !settings.apiKey) {
          // Use simulation
          response = await simulateAPICall(request.content);
        } else {
          // Use real API based on provider selection
          switch(settings.apiProvider) {
            case 'openai':
              response = await callOpenAI(request.content, settings);
              break;
            case 'google':
              response = await callGoogleAI(request.content, settings);
              break;
            case 'anthropic':
              response = await callAnthropic(request.content, settings);
              break;
            default:
              response = await simulateAPICall(request.content);
          }
        }
        
        // Save to history
        saveToHistory(request.content, response);
        
        sendResponse({ success: true, response });
      } catch (error) {
        console.error('API processing error:', error);
        sendResponse({ success: false, error: error.message });
      }
    });
    
    return true; // Keep the message channel open for async response
  }
  
  if (request.action === 'saveSettings') {
    chrome.storage.local.set({ settings: request.settings }, () => {
      sendResponse({ success: true });
    });
    return true;
  }
  
  if (request.action === 'getSettings') {
    chrome.storage.local.get('settings', (data) => {
      sendResponse({ success: true, settings: data.settings });
    });
    return true;
  }
  
  // Other message handlers can be added here
});

// Save content processing to history
function saveToHistory(content, response) {
  chrome.storage.local.get('history', (data) => {
    const history = data.history || [];
    
    // Add new item to history
    history.unshift({
      timestamp: new Date().toISOString(),
      content: content.substring(0, 150) + '...', // Store only a preview
      response: response
    });
    
    // Limit history to 10 items
    if (history.length > 10) {
      history.pop();
    }
    
    // Save updated history
    chrome.storage.local.set({ history });
  });
}

// Simulated API call (used as fallback or for testing)
async function simulateAPICall(content) {
  return new Promise((resolve) => {
    // Simulate API processing time
    setTimeout(() => {
      // This is where you would actually call the LLM API
      // For now, we'll return a mock response
      
      const mockResponse = {
        explanation: `This is a simulated explanation of the content. In a real implementation, 
                      this would be generated by an LLM API based on the extracted content.
                      
                      The content you're trying to understand discusses important concepts
                      that would be simplified and explained clearly in non-technical terms.
                      
                      To truly understand this topic, it's important to focus on the fundamental
                      principles and how they relate to concepts you already understand.`,
        followUpQuestions: [
          "What are the key points from this content?",
          "How would you explain this to someone else?",
          "What questions do you still have about this topic?",
          "Can you relate this to something you already know?"
        ]
      };
      
      resolve(mockResponse);
    }, 1500); // 1.5 second delay to simulate API call
  });
}

// OpenAI API call
async function callOpenAI(content, settings) {
  // Prepare the content (trim if too long)
  const trimmedContent = content.length > settings.maxContentLength 
    ? content.substring(0, settings.maxContentLength) + '...(content truncated)'
    : content;
    
  const apiKey = settings.apiKey;
  
  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: settings.apiModel || 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: `You are a helpful tutor using the Teachme Technique. 
                     Your task is to explain the following content in simple terms that anyone could understand,
                     avoiding jargon and using analogies where helpful.
                     
                     After your explanation, provide 4 follow-up questions that would test the user's understanding
                     and help them identify any gaps in their knowledge.
                     
                     Format your response in two sections:
                     1. Your clear explanation
                     2. Follow-up questions as a numbered list`
          },
          {
            role: 'user',
            content: `Please explain this content in simple terms: ${trimmedContent}`
          }
        ],
        temperature: 0.7
      })
    });
    
    const data = await response.json();
    
    if (!response.ok) {
      throw new Error(data.error?.message || 'Unknown API error');
    }
    
    // Process the API response
    const aiResponse = data.choices[0].message.content;
    
    // Extract explanation and questions from the response
    const splitResponse = processAIResponse(aiResponse);
    
    return splitResponse;
  } catch (error) {
    console.error('OpenAI API error:', error);
    throw error;
  }
}

// Google AI API call (placeholder - implement when needed)
async function callGoogleAI(content, settings) {
  // Implement Google Gemini API integration
  return simulateAPICall(content);
}

// Anthropic API call (placeholder - implement when needed)
async function callAnthropic(content, settings) {
  // Implement Anthropic Claude API integration
  return simulateAPICall(content);
}

// Process AI response to extract explanation and questions
function processAIResponse(aiResponse) {
  // This is a simple parser - you might want to improve this based on actual API responses
  
  // Default values in case parsing fails
  let explanation = aiResponse;
  let followUpQuestions = [];
  
  // Try to extract questions (looking for numbered lists, bullet points, etc.)
  const questionMatches = aiResponse.match(/\d+\.\s+(.+?)(?=\d+\.|$)/gs) || 
                          aiResponse.match(/\n-\s+(.+)/g) ||
                          aiResponse.match(/\n•\s+(.+)/g);
  
  if (questionMatches && questionMatches.length >= 3) {
    // If we found what looks like questions, extract them
    followUpQuestions = questionMatches.map(q => q.trim().replace(/^\d+\.\s+|-\s+|•\s+/, ''));
    
    // Remove the questions from the explanation
    const questionsStartIndex = aiResponse.indexOf(questionMatches[0]);
    if (questionsStartIndex > 0) {
      explanation = aiResponse.substring(0, questionsStartIndex).trim();
    }
  }
  
  return {
    explanation: explanation,
    followUpQuestions: followUpQuestions
  };
}

// Listen for installation and update events
chrome.runtime.onInstalled.addListener(({ reason }) => {
  if (reason === 'install') {
    // Open onboarding page when extension is first installed
    chrome.tabs.create({
      url: 'onboarding.html'
    });
  }
});